### PR TITLE
Update dependabot configuration

### PR DESCRIPTION
**Pull request by gaby**
- Added support for tracking updates for `Github-Actions` via dependabot
- Added support for auto-merging dependabot PR's

### CODE REVIEW

**Comment by efectn** [comment]
Can you check the indention

**Comment by gaby** [comment]
> Can you check the indention

For some reason it doesnt like those keys, even though I copy them from another fiber repo. Let me check again...

**Comment by gaby** [comment]
So, it turns out that automerged was disable by Github. The reason it works in other Fiber repos is because they are not using the dependabot validator (Ex: boilerolate repo).

More info here: https://github.com/dependabot/dependabot-core/issues/1973

The recommended way to auto merge now is via Github Actions as Fiber does in several repos.

**Comment by efectn** [comment]
I think we can add automerge action to this repo

**Comment by gaby** [comment]
> I think we can add automerge action to this repo

Ok, let me add the file to this sams PR then.

**Comment by gaby** [comment]
Done, added a copy of this one: https://github.com/gofiber/contrib/blob/main/.github/workflows/dependabot_automerge.yml

**Review by efectn — APPROVED** [review]

**Comment by gaby** [comment]
Repo needs a secret/token for `wait_for` to work properly.

**Comment by efectn** [comment]
> Repo needs a secret/token for `wait_for` to work properly.

@ReneWerner87 can you check it

**Comment by ReneWerner87** [comment]
Sure

**Comment by ReneWerner87** [comment]
I think I still have to activate the token for the repository
also the regex for the wait check has to be changed, because the job name is "Test" and not "Tests".
Or the job must be renamed

I will do it tomorrow

**Comment by gaby** [comment]
> I think I still have to activate the token for the repository also the regex for the wait check has to be changed, because the job name is "Test" and not "Tests". Or the job must be renamed
> 
> I will do it tomorrow

Thanks! I just updated the job name to `Tests`.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/keyauth/blob/master/.github/workflows/test.yml#L4
Is also wrong

**Comment by gaby** [comment]
> https://github.com/gofiber/keyauth/blob/master/.github/workflows/test.yml#L4 Is also wrong

Updated, also added more Go versions to matrix. Seems like this middleware needs some unit-testing byt that should be cover by a different PR.

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
